version: '3.2'

networks:
  web:
    external: true
  oc_store:
    external: false

services:
  webserver:
    image: nginx:alpine
    container_name: nginx_ocstore
    working_dir: /app/upload
    depends_on:
      - php
    networks:
      - web
      - oc_store
    volumes:
      - ./upload:/app/upload
      - ./.docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx_ocstore.entrypoints=http
      - traefik.http.routers.nginx_ocstore.rule=Host(`ocstore.localhost`)

  php:
    build: .docker/dev/php
    container_name: php_ocstore
    working_dir: /app
    env_file: .env.dev
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - oc_store

  db:
    image: mysql:5.7.33
    container_name: db_oc_store
    volumes:
      - ./.docker/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: oc_store
      MYSQL_USER: oc_store
      MYSQL_PASSWORD: oc_store
    ports:
      - "7777:3306"
    networks:
      - oc_store
      - web

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      MYSQL_ROOT_PASSWORD: '1'
    container_name: pma_ocstore
    links:
      - db:db
    networks:
      - oc_store
      - web
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.pma_ocstore.entrypoints=http
      - traefik.http.routers.pma_ocstore.rule=Host(`pma.ocstore.localhost`)


